CREATE TABLE [dbo].[Family] (
    [Periodoacademico]   CHAR (10)     NOT NULL,
    [alumnogrupo]        CHAR (10)     NOT NULL,
    [Familia]            VARCHAR (100) NOT NULL,
    [Vinculo]            CHAR (100)    NOT NULL,
    [Apellidos]          VARCHAR (50)  NULL,
    [Nombres]            VARCHAR (50)  NULL,
    [Direccion]          CHAR (100)    NULL,
    [ciudad]             CHAR (100)    NULL,
    [Pais]               CHAR (50)     NULL,
    [codigopostal]       CHAR (50)     NULL,
    [emailcasa]          CHAR (50)     NULL,
    [emailoficina]       CHAR (50)     NULL,
    [Tipodocumento]      VARCHAR (20)  NULL,
    [documentoidentidad] CHAR (20)     NOT NULL,
    [fechanacimiento]    DATETIME      NULL,
    [PaisNacimiento]     CHAR (50)     NULL,
    [Nacionalidad]       CHAR (50)     NULL,
    [Idioma]             CHAR (50)     NULL,
    [GradoInstruccion]   VARCHAR (50)  NULL,
    [telefono01]         CHAR (20)     NULL,
    [telefono02]         CHAR (20)     NULL,
    [telefonocelular]    CHAR (20)     NULL,
    [fax]                CHAR (20)     NULL,
    [IdiomaSecundario]   CHAR (30)     NULL,
    [Grupo]              INT           NULL,
    [RutaFoto]           CHAR (150)    NULL,
    [imgfamily]          IMAGE         NULL,
    [CheckReference]     INT           NOT NULL,
    [FechaCreacion]      DATETIME      NULL,
    [UsuarioCreacion]    VARCHAR (20)  NULL,
    CONSTRAINT [PK_Family] PRIMARY KEY CLUSTERED ([Periodoacademico] ASC, [alumnogrupo] ASC, [Familia] ASC, [Vinculo] ASC, [documentoidentidad] ASC, [CheckReference] ASC)
);

