CREATE TABLE [dbo].[Students] (
    [Periodoacademico]            CHAR (10)    NOT NULL,
    [GradoCodigo]                 CHAR (6)     NOT NULL,
    [Seccion]                     CHAR (2)     NULL,
    [alumnogrupo]                 CHAR (10)    NULL,
    [Familia]                     VARCHAR (50) NULL,
    [Grado]                       CHAR (50)    NULL,
    [rol]                         CHAR (1)     NULL,
    [Alumnocodigo]                CHAR (10)    NOT NULL,
    [Apellidos]                   VARCHAR (50) NOT NULL,
    [Nombres]                     VARCHAR (50) NULL,
    [fechanacimiento]             DATETIME     NULL,
    [FechaNacimientoString]       CHAR (50)    NULL,
    [fechaingreso]                DATETIME     NULL,
    [lugarnacimiento]             CHAR (50)    NULL,
    [Programa]                    VARCHAR (50) NULL,
    [Sexo]                        VARCHAR (20) NULL,
    [Nacionalidad]                CHAR (50)    NULL,
    [Idioma]                      CHAR (50)    NULL,
    [IdiomaSecundario]            CHAR (50)    NULL,
    [email]                       CHAR (50)    NULL,
    [Seguromedico]                CHAR (50)    NULL,
    [SeguroMedicoPoliza]          CHAR (20)    NULL,
    [SeguroMedicoFechaExpiracion] DATETIME     NULL,
    [EmergenciaContacto]          CHAR (50)    NULL,
    [EmergenciaTelefono]          CHAR (20)    NULL,
    [EmergenciaContacto2]         CHAR (50)    NULL,
    [EmergenciaTelefono2]         CHAR (20)    NULL,
    [CodigoInterno]               VARCHAR (20) NOT NULL,
    [RutaFoto]                    CHAR (150)   NULL,
    [imgstudents]                 IMAGE        NULL,
    [Gate]                        CHAR (20)    NULL,
    [CheckReference]              INT          NOT NULL,
    [FechaCreacion]               DATETIME     NULL,
    [UsuarioCreacion]             VARCHAR (20) NULL,
    CONSTRAINT [PK_Students] PRIMARY KEY CLUSTERED ([Periodoacademico] ASC, [GradoCodigo] ASC, [Alumnocodigo] ASC, [Apellidos] ASC, [CodigoInterno] ASC, [CheckReference] ASC) WITH (FILLFACTOR = 90)
);

