

CREATE VIEW [dbo].[VW_Syn_Photo_Family]
as
SELECT [Periodoacademico]
      ,[alumnogrupo]
      ,[Familia]
      ,[Vinculo]
      ,[Apellidos]
      ,[Nombres]
      ,[Direccion]
      ,[ciudad]
      ,[Pais]
      ,[codigopostal]
      ,[emailcasa]
      ,[emailoficina]
      ,[Tipodocumento]
      ,[documentoidentidad]
      ,[fechanacimiento]
      ,[PaisNacimiento]
      ,[Nacionalidad]
      ,[Idioma]
      ,[GradoInstruccion]
      ,[telefono01]
      ,[telefono02]
      ,[telefonocelular]
      ,[fax]
      ,[IdiomaSecundario]
      ,[Grupo]
      ,[RutaFoto]
      ,[imgfamily]
      ,[CheckReference]
  FROM [Photos].[dbo].[Family]


