
CREATE VIEW [dbo].[VW_Syn_Photo_Staff]
as
SELECT [Periodoacademico]
      ,[empleado]
      ,[Apellidos]
      ,[Nombres]
      ,[Sexo]
      ,[PaisNaciimiento]
      ,[DepartamentoNacimiento]
      ,[provincianacimiento]
      ,[DistritoNacimiento]
      ,[fechanacimiento]
      ,[Direccion]
      ,[Departamento]
      ,[Provincia]
      ,[CodigoPostal]
      ,[Telefono]
      ,[Fax]
      ,[Ceular]
      ,[TipoDocumento]
      ,[documento]
      ,[nacionalidad]
      ,[CorreoElectronico]
      ,[GrupoSanguineo]
      ,[NombreEmergencia]
      ,[DireccionEmergencia]
      ,[TelefonoEmergencia]
      ,[celularemergencia]
      ,[NombreEmergencia2]
      ,[DireccionEmergencia2]
      ,[TelefonoEmergencia2]
      ,[CelularEmergencia2]
      ,[CentroCostos]
      ,[Proyecto]
      ,[correointerno]
      ,[anexo]
      ,[CodigoUsuario]
      ,[TipoPlanilla]
      ,[TipoTrabajador]
      ,[FechaIngreso]
      ,[fechacese]
      ,[fechareingreso]
      ,[TipoContrato]
      ,[FechaInicioContrato]
      ,[FechaFinContrato]
      ,[numerocontrato]
      ,[NombreCarnet]
      ,[ApellidoCarnet]
      ,[PuestoCarnet]
      ,[tipohorario]
      ,[Cargo]
      ,[CategoriaFuncional]
      ,[flagcentroformacion]
      ,[Niveleducativo]
      ,[CategoriaOcupacional]
      ,[RutaFoto]
      ,[imgstaff]
      ,[CheckReference]
  FROM [Photos].[dbo].[Staff]


